facebook/regenerator

runtime.js

This implements the first alternativ in #148, e.g. use a helper function for all try catch in the runtime.

Add try/catch helper to fix #148

---

runtime-module.js
runtime.js

@sebmck @appden does this work for you?
I'm a little worried that this will be a breaking change for users who expect `regeneratorRuntime` to be defined globally for them. What if we kept defining it globally in https://github.com/facebook/regenerator/blob/master/runtime.js, but provided another file that you could `require` as a proper module instead?
Fixes #165.
Fixes #166.

Allow the runtime to be required as a module, and make it strict-mode-compliant.

---

main.js

There is a bug in brfs which disallows passing variables to fs.readFileSync.
This means that anyone using this module with Browserify will have a breaking
build. This can be fixed by using the value of remote.path directly, which,
while not optimal, solves the issue while the bug for fs.readFileSync is fixed.
I'm not sure if this PR is the right way to go about it, or to wait until brfs
addresses the issue. This PR is what I am using to fix my current build.
See more here: https://github.com/substack/brfs/issues/36

Use the value for remote.path directly in fs.readFileSync

---

main.js

This is the fix for bug introduced by https://github.com/facebook/regenerator/pull/177. Code reads file in sync way and it assumes `path` variable is pointing to `path` module, but as there is another `path` declaration within the same scope (`var path = new types.NodePath(ast);`), it gets hoisted on top and so `path` becomes `undefined`. It leads to following JS error:
```
TypeError: Cannot call method 'join' of undefined
```

Fix JS hoisting issue by using different var name

---

runtime-module.js

This fixes #183.
Not all browsers -- specifically Safari -- support calling `Object.hasOwnProperty` on the global `self` object in a worker. This is a workaround.

Use `getOwnPropertyNames` to check for runtime global

---

runtime.js

This allows for libraries and applications 3 or 4 layers up to be able to use generators in a domain and have the domain context be persisted.
---
> In order to accept your pull request, we need you to submit a CLA. You only need to do this once, so if you've done this for another Facebook open source project, you're good to go. If you are submitting a pull request for the first time, just let us know that you have completed the CLA and we can cross-check with your GitHub username.
I've completed the CLA.

Bind the step function to the active domain (if present)

---

runtime.js

Delete was causing deoptimization due to backing class change and was unnecessary as this field was explicitly initialized to undefined and was not being checked for existence as best I can tell.
When combined with #207 saw a 40x throughput improvement under FF, from 39k operations/sec to 1.6M ops/src on http://kpdecker.github.io/six-speed/

Reset rather than delete sent field on next

---

runtime.js

We know that they will not exist at this point so the overhead of iterating and running the has own property check is unnecessary.
This led to 4-16x speed increases for the Babel generator tests defined here:
http://kpdecker.github.io/six-speed/

Do not reset temp vars on Context init

---

runtime-module.js

For ie8, deleting window properties only works you delete them as a variable from the global scope:
i.e.
```
window.foo = 1; 
delete foo; // works
window.bar = 1;
delete window.bar //errors
```

Wrap global delete in try/catch for ie8

---

runtime.js

Regenerator has problem with *infinity loops*, for example, [sandbox](http://facebook.github.io/regenerator/) fail with next code:
```js
setTimeout(async function () {
while (true) {
await Promise.resolve()
}
}, 0)
```
This PR solve this problem, also (probably) it's decreases memory consumption on sequence of await's.

Infinity loop problem

---

main.js

via #20 
At the moment it seems it's not possible to handle errors emitted on a regenerator transformation through browserify.
So:
```js
browserify(src)
.transform(require('regenerator'))
.bundle(function (err, bundle) {
if (err) { return handleError(err); }
handleBundle(bundle);
});
```
where `handleError` never gets triggered and the application crashes beforehand because apparently regenerator is throwing an Error instead of emitting through this.emit('error', new Error())
more on how to achieve this: 
https://github.com/substack/node-browserify/blob/071642ad9cbb44cb530d43edfac17c5077a9442c/test/tr_error.js#L11-L13

Allow Browserify to handle regenerator errors #20

---

packages/regenerator-runtime/runtime.js

> Added defense codes to prevent breaking async/await statements at the IE8 caused by the outerFn.
> @Pitzcarraldo
From https://github.com/babel/babel/pull/3445 and https://phabricator.babeljs.io/T7028

Added defense code to prevent breaking async/await statements at IE8

---

package.json

Fix WARN
```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

Bump commoner version to ~0.10.4

---

packages/regenerator-runtime/runtime.js
test/non-native.js

Thanks so much for your work on such a cool project!
I found what I think is a spec-compliance bug with the generator prototype chain. According to section 25.3.1 (emphasis mine):
> The Generator prototype object is the %GeneratorPrototype% intrinsic. It is also the initial value of the prototype property of the %Generator% intrinsic (the GeneratorFunction.prototype).
> 
> &lt;snip&gt;
> 
> **The value of the [[Prototype]] internal slot of the Generator prototype object is the intrinsic object %IteratorPrototype% (25.1.2)**. The initial value of the [[Extensible]] internal slot of the Generator prototype object is true.
This means that` %GeneratorPrototype%` should **not** have a `Symbol.iterator` property, but its prototype should. In addition, `%GeneratorPrototype%'`s prototype should …

Fix generator prototype chain to more correctly match ES2015 spec

---

packages/regenerator-transform/package.json

If we move the implementation maybe we want to be as close as possible to what it was before?
https://github.com/babel/babel/blob/26b4e0909ef8ec3a45b08f2a475124ed83defdac/package.json#L51-L66
```
{
"comments": false,
"presets": [
[
"es2015",
{
"loose": true
}
],
"stage-0"
],
"plugins": [
"./scripts/add-module-exports",
"transform-runtime",
"transform-class-properties",
"transform-flow-strip-types"
],
}
the other plugins/presets won't matter if the syntax isn't used so we can ignore that.

compile with loose mode

---

packages/regenerator-transform/package.json

I am getting an error when I try to run my webpack build.
```
Error in config file!
Error: Options {"loose":true} passed to /Users/my-repo/node_modules/babel-preset-es2015/lib/index.js which does not accept options.
(While processing preset: "/Users/my-repo/node_modules/babel-preset-es2015/lib/index.js")
(While processing preset: "/Users/my-repo/node_modules/babel-preset-es2015/lib/index.js")
```
[This PR](https://github.com/facebook/regenerator/commit/acf11c4218088df58cc7c80d63d5ce2c48e152c7) added `{ "loose": true }` to `es2015` preset, but loose is not supported until [es2015 v6.13.0](https://github.com/babel/babel/blob/master/CHANGELOG.md#v6130-2016-08-04).
I updated `babel-preset-es2015` to latest v6.18.0 and all the tests pass.

update babel-preset-es2015 to 6.18.0

---

packages/regenerator-transform/src/meta.js

Using arrow functions inside generators:
```javascript
function gen* {
const a = () => { 
return 1 
};
};
```
throws:
```
Error: src/index.js: unknown Expression of type "ArrowFunctionExpression"
at /Users/aqson/Development/temp/babel-preset-env-issue-160/node_modules/regenerator-transform/lib/emit.js:1035:15
```
But works fine with `FunctionExpression`s and arrow functions without `BlockStatement`s:
```
function gen* {
const a = () => 1;
};
function gen2* {
const a = function () {
return 1;
};
};
```
The root of the problems lies in the `explodeStatement` method where we check [node for the leaps](https://github.com/facebook/regenerator/blob/master/packages/regenerator-transform/src/emit.js#L386) and 2 of working cases returns `false`, but the one with ArrowFunctionExpression + …

Add ArrowFunctionExpression to opaqueTypes

---

packages/regenerator-transform/src/replaceShorthandObjectMethod.js
packages/regenerator-transform/src/visit.js
test/run.js
test/tests-node4.es6.js
test/tests.es6.js

I think I found a bug with `transformer-regenerator` when it is used without `transform-es2015-shorthand-properties`. If you take the following input code:
```
var o = {
*foo() {
return "foo";
}
};
```
and apply **only** `transform-regenerator`, you get:
```
var o = {
foo() {
return regeneratorRuntime.wrap(function _callee$(_context) {
while (1) switch (_context.prev = _context.next) {
case 0:
return _context.abrupt("return", "foo");
case 1:
case "end":
return _context.stop();
}
}, _callee, this);
}
};
```
Note that there is a reference to `_callee` at the end, but `_callee` is never defined. This causes a ReferenceError when the code is run.
If you add `transform-es2015-shorthand-properties` to the plugin list, you instead get this result:
```
var o = {
foo: …
```

Fix for bug when transform-regenerator is run without transform-es2015-shorthand-properties

---

packages/regenerator-transform/package.json

This includes support for es2016 & es2017 and we are also more or less recommending everyone to use env instead of `latest`- or `es20XX`-presets.
If at some point node <4 might be dropped in this package, we could also easily target node4 as environment, which excludes some transforms.
Right now the transformed sourcecode is exactly the same.

Use babel-preset-env instead of babel-preset-es2015

---

package.json
packages/regenerator-transform/src/visit.js
test/regression.js
test/run.js

In the case that the generator or the async function is initially an arrow function and uses only a rest param, the babel es2015 transforms will replace the arrow with a function and the rest param with arguments. regenerator-transform will later also replace and move the arguments. In the end babel will hoist the arguments back up, but to the wrong level.
Thats a little bit complicated to describe, maybe better I show it with code:
1. initial
```js
function test(fn) {
return async (...args) => {
return fn(...args);
};
}
```
2. arrow transform
```js
function test(fn) {
return async function (...args) {
return fn(...args);
};
}
```
3. rest transform
```js
function test(fn) {
return async function () {
return fn.apply(this, arguments);
};
}
```
4. regenerator transform (this is what it …

Fix hoisting of arguments

---

packages/regenerator-runtime/runtime.js

Attempt to address #274. We're basically checking whether or not the `NativeIteratorPrototype`'s next function is the bad `LegacyIteratorNext` function. If it is, then we choose to use the polyfill. If it's not and we would have otherwise been using the native iterator, then we use the native iterator implementation.
Running the browser tests in `test/index.html` confirms that things work in Firefox < 45, in Firefox > 45 and in Chrome. Thoughts?

Resolve yield * issues for Firefox < 45

---

packages/regenerator-transform/src/visit.js

Babel 7 onward, a name is mandatory to facilitate plugin ordering

Inject name into plugin

---

packages/regenerator-runtime/runtime-module.js
packages/regenerator-runtime/runtime.js

Take advantage of sloppy mode, aka non-strict mode, where unbound functions are called with the global object as `this`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Securing_JavaScript

Simplify reference to the global object

---

packages/regenerator-transform/src/emit.js
packages/regenerator-transform/src/hoist.js
packages/regenerator-transform/src/replaceShorthandObjectMethod.js
packages/regenerator-transform/src/util.js
packages/regenerator-transform/src/visit.js
test/replaceWith-falsy.js
test/run.js

Before, when regenerator is run with the following input:
```js
async function foo() {
for (let i; i;);
}
```
it throws this error:
You passed `path.replaceWith()` a falsy node, use `path.remove()` instead
With this change, the following code is output:
```js
function foo() {
var i;
return regeneratorRuntime.async(function foo$(_context) {
while (1) {
switch (_context.prev = _context.next) {
case 0:
for (; i;) {}
case 1:
case "end":
return _context.stop();
}
}
}, null, this);
}
```
Fixes https://github.com/babel/babel/issues/4953

Don't pass falsy nodes to `path.replaceWith()`

---

package.json
packages/regenerator-transform/src/visit.js
test/tests.transform.js

(see also #301 for old discussion)
with the current code, this:
```
export function* test() {}
export function* abc() {}
```
compiles to this:
```
var _marked = [test, abc].map(regeneratorRuntime.mark);
export function test() {
return regeneratorRuntime.wrap(function test$(_context) {
while (1) {
switch (_context.prev = _context.next) {
case 0:
case "end":
return _context.stop();
}
}
}, _marked[0], this);
}
export function abc() {
return regeneratorRuntime.wrap(function abc$(_context2) {
while (1) {
switch (_context2.prev = _context2.next) {
case 0:
case "end":
return _context2.stop();
}
}
}, _marked[1], this);
}
```
because of the `[test, abc].map` call `uglifyjs` won't strip out `test` or `abc` if they're never actually imported (`webpack` does correctly identify them as non-imported …

refactor mark declaration, add __PURE__ comments (#286)

---

packages/regenerator-transform/src/index.js
packages/regenerator-transform/src/visit.js

Alternate approach for https://github.com/facebook/regenerator/pull/311 that will avoid breaking changes for Babel 6.x

Only export plugin name for Babel>=7.x

---

packages/regenerator-transform/package.json

ideally would update the packages to v7.0 alpha too but can do that later I guess?
and do we need private if we have `Symbol`?

Breaking: remove transform-runtime

---

.travis.yml
packages/regenerator-transform/package.json
packages/regenerator-transform/src/emit.js
packages/regenerator-transform/src/hoist.js
packages/regenerator-transform/src/index.js
packages/regenerator-transform/src/leap.js
packages/regenerator-transform/src/meta.js
packages/regenerator-transform/src/replaceShorthandObjectMethod.js
packages/regenerator-transform/src/util.js
packages/regenerator-transform/src/visit.js

Fixes #328.
cc @hzoo @loganfsmyth 
Instead of passing the `context.types` object throughout `regenerator-transform` (really invasive), or wrapping every module with some sort of constructor function (which would require abandoning both `require` and `import`), I decided to use stack-based local state in the `util.js` module, so that `currentTypes` can be retrieved from anywhere, as long as there's a function wrapped with `util.wrapWithTypes` currently on the stack. Since `regenerator-transform` is entirely synchronous, this turns out to be an easy property to enforce, with only one call to `util.wrapWithTypes`.

Use plugin-provided context.types instead of importing babel-types.

---

packages/regenerator-transform/src/emit.js

Fixes #342 
Refs https://github.com/devtools-html/debugger.html/issues/5561, https://github.com/devtools-html/debugger.html/issues/6400
It doesn't look like there are any tests that validate the source mappings, but if you feel strongly about it I'd be happy to explore adding some.
Like I mentioned in #342, stuff like https://github.com/facebook/regenerator/blob/58c0eca04145da79c263194a605ca5a6294a72b4/packages/regenerator-transform/src/emit.js#L1162 also loses the location because it replaces the nodes with fresh ones that don't have a location, but I'm leaving that for now since it's a more aggressive change.

Preserve the location of the replaced 'yield' nodes.

---

package-lock.json
package.json
packages/regenerator-transform/src/emit.js
packages/regenerator-transform/src/hoist.js
packages/regenerator-transform/src/visit.js
test/run.js

**Motivation**
Duplicated AST nodes were causing some obscure, hard to find bugs and they got forbidden in [babel's output](https://github.com/babel/babel/pull/7149).
At the moment this is unfortunately only [checked in core tests](https://github.com/babel/babel/blob/d383659ca6adec54b6054f77cdaa16da88e8a171/packages/babel-helper-transform-fixture-test-runner/src/index.js#L128). Because regenerator is used by babel as core transform and because it produces numerous duplicated nodes (only 1 "kind" of them intentionally) some nasty lines got introduced to babel's check functions to allow regenerator-created nodes.
I'd like to get rid of those nasty lines with this PR 😉

Avoid reuse of AST nodes by making defensive clones

---

packages/regenerator-runtime/runtime.js
test/async.js
test/run.js

I noticed this bug after realizing that we were not running the `test/async.js` tests natively in any version of Node. After enabling the native async tests, there was one test that failed in native Node, and it was a test that exercised yielding a rejected `Promise` in an async generator function.
In an async generator function,
```js   
yield <promise>
```    
should have the semantics of
```js   
yield await <promise>
```    
per [TC39 consensus](https://github.com/tc39/tc39-notes/blob/master/es8/2017-05/may-25.md#15iva-revisiting-async-generator-yield-behavior). In other words, if `<promise>` is rejected, that rejection should be thrown back into the async generator function, rather than being exposed as a normal value to the consumer of the function (as this code was previously …

Await yielded promises in async generator functions.

---

.travis.yml
package-lock.json
package.json
test/run.sh

With any luck, simply updating to the latest (release candidate) version of Lerna will fix the problems reported by @Benjamin-Dobell [here](https://github.com/facebook/regenerator/pull/346#issuecomment-406909615). Properly linking local packages is definitely Lerna's job, and there's nothing particularly unusual about the organization of this repository.

Replace unreliable Lerna bootstrapping with a simple test/run.sh script.

---

packages/regenerator-runtime/runtime-module.js
packages/regenerator-runtime/runtime.js

Fix unsafe-eval CSP violation - closes #336

---

packages/regenerator-transform/src/index.js
packages/regenerator-transform/src/leap.js
packages/regenerator-transform/src/meta.js
packages/regenerator-transform/src/visit.js

I think @cito125 (`mad_babeler` on BabelJS Slack) has already been in contact with you about some issues we're having using `regenerator-transform` together with Babel 7, React Native and `proxyquire`. Turns out that replacing the `require` statements in the source with ES module `import` statements solves our issue, as we no longer end up importing the `emit.js` source twice (which causes issues with the type assertion on line 131 of `leap.js`.
Hopefully this is a pretty non-controversial change to update all the `require` statements in the package with `import`s instead!

Replace "require" with "import" in regenerator-transform source

---

packages/regenerator-transform/src/visit.js
test/async.js
test/tests.es6.js

Fixes babel/babel#4056
As explained in that issue, regenerator prevents engines from collectiong `this` even when it is not used, causing a memory leak.
Input:
```js
function f() {
return async _ => {};
}
function g() {
return async _ => this;
}
```
<details>
<summary>Output before this PR:</summary>
```js
function f() {
return _ => {
return regeneratorRuntime.async(function _callee$(_context) {
while (1) switch (_context.prev = _context.next) {
case 0:
case "end":
return _context.stop();
}
}, null, this);
};
}
function g() {
return _ => {
return regeneratorRuntime.async(function _callee2$(_context2) {
while (1) switch (_context2.prev = _context2.next) {
case 0:
return _context2.abrupt("return", this);
case 1:
case "end":
return _context2.stop();
}
}, null, this);
};
}
```
</details> …

Don't capture "this" when not needed

---

.travis.yml
package-lock.json
packages/regenerator-runtime/package.json
packages/regenerator-runtime/runtime.js
test/run.sh
test/runtime.js

In #353, I simplified the implementation of `regenerator-runtime` by converting `runtime.js` to a normal CommonJS module. No more global object detection, and no more sneaky capture/deletion of `regeneratorRuntime`.
Unfortunately, folks who use only `@babel/polyfill` and not `@babel/transform-runtime` may have existing code that relies on a global `regeneratorRuntime` variable. That code will eventually disappear (🤞), but in the meantime we can continue supporting it by simply ensuring that `regeneratorRuntime` is defined globally as a side-effect of importing `regenerator-runtime`.
This turns out to be much easier than detecting the global object, as long as `runtime.js` runs as a non-strict CommonJS module. See my code comments for another fallback solution that should cover all …

Define regeneratorRuntime globally as a side-effect, again.

---

packages/regenerator-transform/src/hoist.js
test/tests.transform.js

Fixes babel/babel#6923, fixes babel/babel#8899, fixes babel/babel#8525
When hoisting variables, regenerator transforms`let a = 2;` to `a = 2;` and then injects `var a` at the beginning of the generator function scope.
Babel isn't really good at keeping the scope synchronized with the AST (and we won't fix it for a long time; it's probably the hardest thing to fix): for this reason, sometimes it throws when injecting `var a` because it thinks that `let a` is still there.
Manually removing the old bindings fixes the bug.
Note that this bug is only present when using `regenerator-transform` without `@babel/plugin-transform-block-scoping` (and thus it isn't reproducible when using `regenerator-preset`), because `@babel/plugin-transform-block-scoping` transforms `let`->`var` and `var`s can be …

Remove old bindings when hoisting vars

---

package-lock.json
package.json
packages/regenerator-transform/src/visit.js
test/tests.transform.js

In https://github.com/facebook/regenerator/pull/368, I changed `regenerator-transform` to remove bindings which are hoisted, since it caused problems when they were registered again.
Nothing in this plugin actually registered them, but sometimes Babel re-traverses the scope and registers declaration which weren't already registerd (this usually happens when a function node is discarded and re-created, I think). For this reason, this code used to throw:
```js
async function foo() {
(async function (number) {
const tmp = number
})
}
```
because when Babel did re-crawl the bindings, it already had a `tmp` binding registered (for `const tmp`) and tried to register a new one with the same name (for the hoisted `var tmp`).
Unfortunately we can't always rely on something to trigger the scope …

Register new bindings when hoisting vars

---

packages/regenerator-preset/LICENSE
packages/regenerator-preset/package.json
packages/regenerator-runtime/LICENSE
packages/regenerator-runtime/package.json
packages/regenerator-transform/LICENSE
packages/regenerator-transform/package.json

Corporate legal was unsatisfied with the license only being found package.json and not directly accessible in full from within the individual distributed packages (since "the root directory of this source tree" is not present in the distributed packages). This pull request adds the license-files to them as well as updates the patch-levels of the distributed package versions in preparation for `npm publish`.
Resolves: #354

Appeasing corporate legal department

---

packages/regenerator-runtime/runtime.js
packages/regenerator-transform/src/visit.js
test/async-custom-promise.js
test/run.js

This makes it possible to run `@babel/plugin-transform-runtime` and `@babel/preset-env`'s `useBuiltIns` on `regenerator`'s output to provide a Promise polyfill in old browsers. 
Fixes babel/babel#10678, babel/babel#10830

Pass Promise as a parameter to regeneratorRuntime.async()

---

packages/regenerator-runtime/README.md

Importing files in a package requires explicit file extension unless it is defined as package exports, see https://nodejs.org/api/esm.html#esm_package_scope_and_file_extensions

add `.js` extension to file import

---

package-lock.json
package.json
packages/regenerator-transform/src/emit.js
test/run.js
test/tests.es6.js

There are some browsers that support array spread but don't support generators.
**Why did we never realize it?**
The browsers versions that support array spread and the versions that supports generators are _close_:
```json
"transform-spread": {
"chrome": "46",
"edge": "13",
"firefox": "36",
"safari": "10",
"node": "5",
"ios": "10",
"samsung": "5",
"opera": "33",
"electron": "0.36"
},
"transform-regenerator": {
"chrome": "50",
"edge": "13",
"firefox": "53",
"safari": "10",
"node": "6",
"ios": "10",
"samsung": "5",
"opera": "37",
"electron": "1.1"
},
```
Probably no one ever used a browsers query in `preset-env` that included `transform-regenerator` but not `transform-spread`.
**Why did we found this bug now?**
`create-react-app` defaults to `>0.2%, not dead, not op_mini all` for browsers …

Add array spread support

---

packages/regenerator-transform/src/visit.js
test/tests.transform.js

Closes #387. Additional context is available there.
This removes the use of attaching a `_shadowFunctionLiteral` property with a `NodePath` value to a `Node`, which prevents Babel ASTs from being serialized. It doesn't appear to be used by Babel any longer and tests still pass.
Test Plan: `npm test`. Tests enforcing the Babel ast can be serialized were added. Existing tests continue to pass.

Remove _shadowFunctionLiteral use

---

packages/regenerator-transform/package.json
packages/regenerator-transform/src/meta.js
packages/regenerator-transform/src/visit.js

Modern JS engines now support WeakMap.  WeakMaps solve the same problem as the private package, but without needing to tamper with intrinsics to ensure their privacy.
Relaxing this dependency eases compatibility with SES (a secure ECMAScript subset that leaves intrinsics immutable).

Relieve dependency on private package

---

packages/regenerator-runtime/runtime.js
test/non-writable-tostringtag-property.js
test/run.js

This avoids an exception when the new iterator helpers proposal provides a spec-compliant nonwritable Symbol.toStringTag property.
See https://github.com/tc39/proposal-iterator-helpers/issues/115 and https://bugzilla.mozilla.org/show_bug.cgi?id=1644581#c6.
Closes #399.

[Fix] conditionally set `Symbol.toStringTag`, since it's nonwritable

---

packages/regenerator-runtime/runtime.js
test/non-writable-tostringtag-property.js

PR <https://github.com/facebook/regenerator/pull/400> makes it so that once engines start shipping `Iterator.prototype[Symbol.toStringTag]`, then `Object.prototype.toString` will return `[object Iterator]` instead of `[object Generator]` for regenerator’s generator objects.
This fixes that to ensure that it doesn’t happen.

runtime: Use `[[Define]]` for the `Symbol.toStringTag` property

---

packages/regenerator-runtime/runtime.js
test/frozen-intrinsics.js
test/run.js

Fixes #410 
thanks for taking the time to review this change :heart: 
I wasn't sure exactly what platform to target with the tests, feedback welcome
these seemed like the least invasive change to make this work
I tested this locally against a more significant freezing of the intrinsics, built from nodejs internal [freeze_intrinsics](https://github.com/nodejs/node/blob/7c808170f5bf27b2d4a83ae5934b5e231bb5c1bc/lib/internal/freeze_intrinsics.js) and [primordials](https://github.com/nodejs/node/blob/7c808170f5bf27b2d4a83ae5934b5e231bb5c1bc/lib/internal/per_context/primordials.js)
here is a draft PR that includes those additional test utilities https://github.com/facebook/regenerator/pull/412
those tests pass with no additional change to the runtime

Runtime - Support frozen intrinsics

---

packages/runtime/runtime.js

Fixes https://github.com/facebook/regenerator/issues/450.

[runtime] Use `globalThis` before `Function()`

---

lib/visit.js

Don't let Babel incorrectly clone the input AST.

---

.gitignore
packages/transform/src/emit.js
test/async.js
test/class.js
test/run.js
test/tests.es6.js

Classes are more supported than generators, so it's possible that Babel users only compile generators:
```json
"transform-regenerator": {
"chrome": "50",
"opera": "37",
"edge": "13",
"firefox": "53",
"safari": "10",
"node": "6",
"ios": "10",
"samsung": "5",
"electron": "1.1"
},
"transform-classes": {
"chrome": "46",
"opera": "33",
"edge": "13",
"firefox": "45",
"safari": "10",
"node": "5",
"ios": "10",
"samsung": "5",
"electron": "0.36"
},
```
Compiling generators inside uncompiled classes is already supported (generator methods), this PR adds support for uncompiled classes inside generators.
Fixes https://github.com/facebook/regenerator/issues/407

Fix class support inside generators

---

packages/runtime/runtime.js

Fixes https://github.com/babel/babel/issues/14684. We cannot remove the `._invoke` method because it's needed to close over what in the spec are internal slots, but we can at least make it non-enumerable so that it's not visible to most JS APIs.

Make `_invoke` method on generators non-enumerable

---

packages/runtime/runtime.js

Fixes https://github.com/babel/babel/issues/14978. Per [spec](https://tc39.es/ecma262/#sec-generator.prototype.constructor), the `constructor` property is now marked as non-numerable and non-writable.

hide constructor property from prototype

---

.github/workflows/node.js.yml
package-lock.json
package.json
test/run.sh

Fix for the latest release version `0.14.8` which includes wrong `file:` protocol resolutions for internal regenerator packages: 3c485a0cf52cbd43dfddc33f83a84c6d8e0caf6f. Local path resolutions do not work when publishing packages to the public registry:
- https://docs.npmjs.com/cli/v8/configuring-npm/package-json#local-paths
Fixes #613

Fix regenerator packages resolution

---

packages/runtime/runtime.js
test/tests.es6.js

Fixes https://github.com/babel/babel/issues/15177

Require `.next` method on delegate iterator

---

packages/transform/src/emit.js
test/tests.es6.js

Fix crash when compiling `yield` or `await` in sparse array, and add test `should work when yield is in a sparse array` to verify the fix.
Fixes #627.

Fix: `yield` / `await` in sparse array

---

packages/preset/package.json
packages/runtime/package.json
packages/transform/package.json

Update GitHub URL in `package.json`.
Also, the repository links on [npmjs.com](https://www.npmjs.com/) also need to be updated to `main`:
- [regenerator-preset](https://www.npmjs.com/package/regenerator-preset) (This one goes to 404 now :no_mouth:)
- [regenerator-runtime](https://www.npmjs.com/package/regenerator-runtime)
- [regenerator-transform](https://www.npmjs.com/package/regenerator-transform) (Also 404)

Fix: GitHub URL in `package.json`

---

packages/transform/src/emit.js

In Babel 8 we are going to improve validation in the `t.numericLiteral` builder to only allow valid numeric literals, and it will start throwing for `-1` (since `-1` should be represented as an unary expression).

Do not use `-1` to mark uninitialized location numeric literals

---

packages/runtime/runtime.js
test/tests.es6.js

`yield*` an non-iterable value should throw `TypeError`, rather than treating it as an iterator with no values.
Fixes #202.
See also: babel/babel#1648, babel/babel#15172

Fix: `yield*` should throw if not iterable

---

packages/runtime/runtime.js
test/tests.es6.js

Test case found while running test262 with Babel: https://github.com/tc39/test262/blob/467a0fe68f633fabde77df94d993c45e840627a0/test/language/expressions/yield/star-in-rltn-expr.js

Fix yield * of falsy values

---

packages/runtime/runtime.js

related : https://github.com/facebook/regenerator/issues/703
reference link now has 404 error. so i change the link to validated spec document
thank you!!

Fix outdated reference link in `runtime.js`
